Window Manger Refactor
natecraddock/zygrader pull request #39
Opened 2020-10-26 15:28 UTC by natecraddock

This is a large pull request (2,037 additions and 1,778 deletions) so I don't expect each line of code to be closely scrutinized. The files that I care about most for review are:
* `layers.py` (new)
* `events.py` (new)
* `window.py`
* `components.py`

More details on the specifics of the changes are found in #28, but I'll give a brief overview here too:

The major changes here are:
1. The window manager has a stack of ComponentLayer objects. The window's `loop` function iterates through the layers drawing, passing events, and adding/removing layers as needed.
2. Event handling is moved to `events.py` from the Window class
3. The user input is no longer on a separate thread
4. The `layers.py` file contains ComponentLayer objects which are a usability layer between the window manager and the Component objects themselves. These layers allow for easily adding, updating, and changing settings on the components.

Closes #28

2020-10-27 00:34 UTC, teiknsmith requested changes
A few comments that don't fit well with any single group of lines:
- Updating the header to cycle the colors needs some fixes. It's obvious that this was considered and noted, but should be finished. Some particular places to fix/resolve:
    - `window.py` lines 215-217
    - `events.py` lines 115-118
    - `events.py` lines 181-182
- Unused imports. I commented on one specifically, but found multiple while running through, and some aren't available for comment on this commit. We should go through all the files and take care of these.
- `zygrader/utils.py` line 211-212 still uses the old window system
- `versioning.py` has a few function names that conflict with what they do (and even their docstrings). It also feels strange that there are two entry points to `do_versioning` (which is a pretty vague name) and then to separately `show_versioning_message(s)` - I see why this was done, but it would be neat if we could find a way to simplify that.
- The readme needs a big look-at in the `Code Documentation` section.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/class_manager.py
> +from datetime import date
As far as I can tell this import is unused

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/grade_puller.py
>                  "Please have the owner of the file grand read permissions",
```suggestion
                "Please have the owner of the file grant read permissions",
```
Just found this small typo scanning through all the files.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/user.py
> +        # TODO: Use the event manager to handle this case!
Seems like this should be resolved before we merge

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/user.py
> +        row.add_row_radio(editor_name, radio)
To me it would feel more intuitive to have a `add_radio_group` function in `Row` that fills in the appropriate rows from the `Radio`, instead of needing to double for loop here

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/user.py
> +        row.add_row_radio(code, radio)
Same as lines 204-205

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/window.py
>          """Initialize screen and run callback function"""
Is there any reason the docstring is not at the top of this function?

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        pass
If `__init__` doesn't do anything anymore, I would think just get rid of it

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
>          self.options_length = sum([len(o) for o in options]) + len(options) + 2
```suggestion
        self.set_options(options)
```

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +
Including (or not) the date means the fields and format string need to update as well.
```suggestion
        self.__init_fields()
        self.__init_format_str()

```

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        return ScrollableList.Line(index, text, color, sort_index)
This method feel superfluous, creating a `ScrollableList.Line` directly doesn't seem that strange. I personally would replace calls to this function with a direct creation and remove this function.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        self._exit_text = text
This is doing nothing - I believe the intention is that it should modify `_lines[0]`

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        # subset of the original list.
This comment feels like it's carried over from old code, it doesn't seem to match the current functionality of this method.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        # A special action (back, quit, etc.)
I'm pretty sure this should be yeeted, either that or I'm missing something entirely here.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
>          self.set_scroll()
This (with line +741) is repeated multiple times and the functionality it drives at is a little unintuitive. We could abstract a `scroll_to_top` function for usage here and in the other search editing functions.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        # TODO: Handle vertical sizing dependant on _searchable
This is a good TODO to resolve before the merge

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +        # TODO: Can we avoid slicing here?
Seems like a reasonable TODO, but not needed for this pull.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/components.py
> +                        curses.A_DIM)
This is very similar to `FilteredList`'s `draw`, and feels like at least some of the logic could be shared between the two in `ScrollableList`. It's different enough that I'm not sure on this, but think we should consider it.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/events.py
> +UI_CENTERED = 2
These aren't used anywhere. Do they have a future purpose, or should they be deleted?

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/events.py
> +        self.modifier = modifier
`modifier` is not used anywhere anymore

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/events.py
> +        self.use_esc_back = False
Should these not be set using `update_preferences`? (and also `vim_mode` on line 65 if so)

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/events.py
> +        self.mark_mode = False
This isn't used anywhere

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +    The worker_fn should accept a single argument which is the queue.
These lines don't make much sense, they feel like they're related to old code.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +        pass
Should this `raise NotImplementedError` instead of just pass? Or are there cases where a Layer class doesn't need to implement `event_handler`?

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +        self.component.cursor_index = len(text)
I think this logic belongs with the Component in a `set_text` method (and then the component's `__init__` could make use of it too).

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +        self.component.set_message(prompt)
The comment can be deleted, or used and the other line deleted.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +class ListLayer(ComponentLayer, Row, PopupLayer):
It feels very strange that a ListLayer *is a* Row - composition feels more intuitive here

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +        self._callback_args = None
Is there a reason for under instead of dunder for `callback_args`?

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +                self.__callback_fn()
If callback args is defaulted to `()`, this should be able to become
```suggestion
            self.__callback_fn(*self._callback_args)
```

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +    # TODO: move somewhere else?
This seems well enough here, but could be moved to a util group if wanted

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +            # TODO: Handle this event by the window manager?
This section seems good as-is
```suggestion
```

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +class Radio:
`RadioGroup` feels like a more intuitive name for this - as is, it looks like it is similar to `Toggle`, which is just one row, but this class manages a group of toggleable radio items.

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/user.py
> +class PreferenceRadio(ui.layers.Radio):
If `Radio` becomes `RadioGroup`, `PreferenceRadio` should also become `PreferenceRadioGroup`
(`RadioGroup` commented on in `layers.py` line 367)

2020-10-27 00:34 UTC, teiknsmith commented on zygrader/ui/layers.py
> +class Toggle:
`Toggle` is using a very strange combination of function passing and inheritance/overriding functions.
It seems the same functionality could be accomplished with this `Toggle` class being a simple interface with no data members and functions to override:
- is_toggled(): Bool
- toggle(): void

2020-10-27 00:35 UTC, spencerteiknsmith commented on zygrader/class_manager.py
> +from datetime import date
```suggestion
```

2020-10-27 00:40 UTC, spencerteiknsmith commented on zygrader/ui/components.py
> +        self._exit_text = text
This was meant to just be on 678-679, I accidentally grabbed two lines prior as well, but they have nothing to do with this

2020-10-27 00:42 UTC, spencerteiknsmith commented on zygrader/ui/components.py
> +        # A special action (back, quit, etc.)
Should just be line 698 referenced here, not sure why I picked up the other lines as well. I suppose it's okay to say they should be yeeted, but they already have been.

2020-10-27 00:43 UTC, spencerteiknsmith commented on zygrader/ui/events.py
> +        self.modifier = modifier
So we should yeet it, and all references to it

2020-10-27 00:46 UTC, spencerteiknsmith commented on zygrader/ui/layers.py
> +    # TODO: move somewhere else?
Again, this picked up some lines ahead of what I want to comment on - the TODO is tied to lines after this.

2020-10-27 00:46 UTC, spencerteiknsmith commented on zygrader/ui/layers.py
> +            # TODO: Handle this event by the window manager?
This TODO also applied to lines not shown in the preview

2020-10-27 19:34 UTC, natecraddock commented
Thanks for the thorough review!
* All imports are now cleaned & organized
* I think the readme documentation can be done as a step after the merge
* There may be a way to combine the versioning code into a single function again, but I think that would be best left until after the refactor. I did update the name of the function though.

2020-10-27 19:36 UTC, natecraddock commented on zygrader/ui/window.py
>          """Initialize screen and run callback function"""
Just a simple mistake..

2020-10-27 19:44 UTC, natecraddock commented on zygrader/ui/components.py
> +        self._exit_text = text
This is intentional, just not written correctly :)

2020-10-27 20:56 UTC, natecraddock commented
Another thing, I don't care about keeping the the cycling header colors. I know @SeaSaltTree  and @mistBourne1300 have been working with headers & colors. Do either of you have an opinion on removing the header color alternating on keypresses?

2020-10-27 20:58 UTC, natecraddock commented on zygrader/ui/components.py
> +                        curses.A_DIM)
This is good, but I'd rather wait until after the refactor here too.

2020-10-27 21:01 UTC, natecraddock commented on zygrader/ui/events.py
> +        self.mark_mode = False
I had forgotten to call it when unregistering layers. Used now.

2020-10-28 22:47 UTC, natecraddock commented on zygrader/user.py
> +        row.add_row_radio(editor_name, radio)
I want to do this before we make 5.0.0 official, but after the merge.

2020-10-28 23:02 UTC, natecraddock commented
@spencerteiknsmith I've addressed every concern you raised. I also
* Merged with master
* Removed the docs
* Updated the version string to `5.0.0`

Once you are happy with everything just go ahead and accept the pull request. I'd like to do the merge manually, so don't do it through github.

2020-10-28 23:47 UTC, spencerteiknsmith approved these changes

2020-10-29 01:04 UTC, SeaSaltTree commented
I like having colors, but they don't have to alternate.

2020-10-29 01:47 UTC, SeaSaltTree commented
Yesterday I was able to grade and lock emails just fine on the refactor branch. Today, normal zygrader (version 4.9) works. In the virtual environment, under the master branch, it works. But in the virtual environment, under the wm-refactor branch, after checking it out and doing git pull, whenever I click email and grade>lab 6 it goes wack. I'm not sure whether this is just me.
<img width="500" alt="wm-refactor" src="https://user-images.githubusercontent.com/70764441/97515286-5e01f300-1956-11eb-91a5-e1ad74fbf27e.PNG">

2020-10-29 01:59 UTC, natecraddock commented
@SeaSaltTree thanks, just fixed that bug.

2020-10-29 02:04 UTC, closed without merging