Window: Add debug console
natecraddock/zygrader pull request #86
Opened 2021-02-16 20:50 UTC by natecraddock

Adds a debugging console to the window manager. This can be enabled with the `-d` or `--debug` flags to zygrader.

At the moment the height is set to 4 rows and will scroll to show the last 4 rows of output. At this point it is useful enough to include in zygrader, but more could be added in the future.

2021-02-16 22:58 UTC, spencerteiknsmith requested changes

2021-02-16 22:58 UTC, spencerteiknsmith commented on zygrader/ui/window.py
> +        display_rows = self.__debug_lines[-4:]
should probably make use of the height constant

2021-02-17 18:53 UTC, natecraddock commented
Was there anything else here you wanted to look at, or am I good to commit now?

2021-02-17 21:05 UTC, spencerteiknsmith commented
that was all - although the behavior is going to be changed with that cleanup. the value was 4 before, and the constant is defined as 5. I'm not sure if that was intentional and fixes behavior, or if it should be `-(DEBUG_CONSOLE_HEIGHT - 1)`. I'll trust you to check that and make sure everything is as it should be

2021-02-17 21:06 UTC, spencerteiknsmith reviewed
that was all - although the behavior is going to be changed with that cleanup. the value was 4 before, and the constant is defined as 5. I'm not sure if that was intentional and fixes behavior, or if it should be -(DEBUG_CONSOLE_HEIGHT - 1). I'll trust you to check that and make sure everything is as it should be

2021-02-17 21:54 UTC, natecraddock commented
Derp, you're right. The original constant was 4, so that's just a stupid mistake. Thanks!

2021-02-17 22:02 UTC, closed without merging