Remove email and password from config
natecraddock/zygrader pull request #91
Opened 2021-02-26 22:55 UTC by natecraddock

Instead store the auth token in the config. Each time zygrader starts
a request is sent to see if the auth token is valid. If it isn't the
user is again prompted for email and password.

This also removes the "Save Password" user preference.
Logging out simply clears the auth token.

2021-02-26 22:56 UTC, natecraddock commented
There are still some cleanups to do (like the signing in window says "Signing in as ..." with no email. But the main part is finished.

2021-03-01 19:35 UTC, spencerteiknsmith requested changes

2021-03-01 19:35 UTC, spencerteiknsmith commented on zygrader/config/preferences.py
> +    # "password": "",
is there a reason to leave these as comments as opposed to complete removal?

2021-03-01 19:35 UTC, spencerteiknsmith commented on zygrader/user.py
> +    # preferences.set("email", "")
like earlier, we should remove this, no?

2021-03-01 19:35 UTC, spencerteiknsmith commented on zygrader/user.py
>      window = ui.get_window()
can't get at the docstring for a comment, but this is close enough. the docstring needs updated

2021-03-01 19:35 UTC, spencerteiknsmith commented on zygrader/user.py
> +    #     PreferenceToggle("save_password", after_fn=save_password_toggle))
again, comment out vs remove. I would think remove

2021-03-01 19:35 UTC, spencerteiknsmith commented on zygrader/zybooks.py
> +        r = Zybooks.session.get(check_url)
I feel like `requests` probably has some system for passing url params in the query string. that would probably be cleaner than the url building here. if it doesn't exist then this is fine

2021-03-01 20:43 UTC, natecraddock commented on zygrader/config/preferences.py
> +    # "password": "",
derp...

2021-03-03 18:57 UTC, natecraddock commented
Alright, it should be good now. Thanks for catching the comments. I had originally tested this by commenting out lines rather than deleting them, and I missed a good bunch.

Turns out that requests can build the query string which is nice. I still had to format the list as a string myself for the class code, but that's okay.

2021-03-03 19:09 UTC, spencerteiknsmith commented
unless I'm seeing it wrong, the docstring on logout in user.py still references a stored email/password instead of token

2021-03-03 19:10 UTC, natecraddock commented
Yeah I'll fix that before committing

2021-03-03 20:45 UTC, closed without merging